name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3  # Updated to the latest version
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: manas-maheshwari
          outputs: dist/github-snake.svg
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist/github-snake.svg
